### ISSUE TITLE
Update Cake.Git to target Cake.Core 3.0.0 and net7.0 TFM

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake_Git#168]

**Comment by augustoproiete** [comment]
:tada: The changes implemented in response to this issue shipped with **Cake.Git v3.0.0**

The release is available on:

- :rocket: [GitHub Release](https://github.com/cake-contrib/Cake_Git/releases/tag/v3.0.0)
- :package: [NuGet Package](https://www.nuget.org/packages/Cake.Git/3.0.0)
