### ISSUE TITLE
Inconsistency between GitClone aliases

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake_Git#22]
As noted on this StackOverflow question/answer:

http://stackoverflow.com/questions/41048037/how-can-i-go-a-git-clone-operation-using-cake

There are two aliases for `GitClone` that accept a username/password.  These aliases don't create the directory that is being cloned into, which is inconsistent compared to the other aliases.

Can these be made the same?

**Comment by devlead** [comment]
Yes, if there's not a technical reason they should be the same.

**Comment by chitoiur** [comment]
I also noticed this.

**Comment by Roadrunner67** [comment]
I have just filed a PR to solve this issue.
