### ISSUE TITLE
Is it possible to use Cake.Git with SSH?

### ISSUE THREAD

**Issue by marekgd** [cake-contrib/Cake_Git#26]

**Comment by devlead** [comment]
Don't think it is as of now, Cake.Git utilizes [libgit2sharp](https://github.com/libgit2/libgit2sharp) and know SSH support is being worked on but don't think it's released/stable yet.

**Comment by pascalberger** [comment]
Considering that LibGit2Sharp probably [never will support SSH](https://github.com/libgit2/libgit2sharp/pull/1072#issuecomment-212383924), would it be an option to use either [LibGit2Sharp-SSH](https://www.nuget.org/packages/LibGit2Sharp-SSH/) or change the addin to be a wrapper around `git.exe` to allow support of advanced scenarios?
