### ISSUE TITLE
Add support for reading configuration values

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake_Git#37]
It would be nice to have support for reading configuration values (eg. username, email). Basically just a wrapper around `Repository.Config.GetValueOrDefault`.

**Comment by devlead** [comment]
Sure makes sense

**Comment by SeanFarrow** [comment]
Hi,

I'm happy to do this if it's wanted as I need this in a project, so it will get done quickly! feel free to assign me!
 Kind regards 
Sean.

**Comment by devlead** [comment]
Ok @SeanFarrow 👍 I've removed the up for grabs label.

**Comment by pascalberger** [comment]
@SeanFarrow If you implement it as a wrapper around `Repository.Config.GetValueOrDefault` this should answer the question regarding what to return if no value exists.

**Comment by SeanFarrow** [comment]
Ok, this is pretty much finished, how do I deal with the release notes, should I just bump the version to 0.16.0 and edit the file?

**Comment by devlead** [comment]
No keep the PR focused l, I'll fix the release notes when releasing.

**Comment by MihaMarkic** [comment]
Has this been ever implemented?

**Comment by devlead** [comment]
Don't think I've seen a PR for this, have a lot on my backlog  so might have missed it.
