### ISSUE TITLE
[NuGet listing] Project site link incorrectly goes to a fork?

### ISSUE THREAD

**Issue by patridge** [cake-contrib/Cake_Git#46]
I think the project site link for this repo's NuGet package is incorrectly pointing to a fork.

While trying to diagnose an issue, I noticed that the [GitHub project site](https://github.com/WCOMAB/Cake_Git) the [Cake.Git NuGet package](https://www.nuget.org/packages/Cake.Git) links to was actually behind the version of the newest NuGet package: [showing v0.15.0](https://github.com/WCOMAB/Cake_Git/blob/fa1c1c6d0330c25e319332f0985e09685816657d/src/SolutionInfo.cs) rather than the live version of v0.16.0. When I clicked through to the source of the fork, though, that repo was on [v0.16.0](https://github.com/cake-contrib/Cake_Git/blob/9909f8f2a1b6244111e7ff15278d7495d177f0f7/src/SolutionInfo.cs#L13).

**Comment by devlead** [comment]
@patridge yip we just recently moved the addin to cake-contrib org, did quick release after that for Cake 0.22.0 compat, next release will have correct links, icon and proper framework monikers.

**Comment by devlead** [comment]
@patridge this as been addressed in the 0.16,1 release.
