### ISSUE TITLE
Build errors for .NET 4.5

### ISSUE THREAD

**Issue by johnkors** [cake-contrib/Cake_Git#48]
Hi, I guess .net 4.5 support was removed recently or something? Breaking change?

```
λ build
Preparing to run build script...
Running build script...
Analyzing build script...
Processing build script...
Installing tools...
Installing addins...
Could not find any assemblies compatible with .NETFramework,Version=v4.5.
Error: Failed to install addin 'Cake.Git'.
```

**Comment by johnkors** [comment]
Ah, I see - there was a release of this add-in and I didn't specify a version explicitly. So it started failing when you released it just now.

Fails:
> #addin nuget:?package=Cake.Git&version=0.16.1 

Works:
> #addin nuget:?package=Cake.Git&version=0.16.0

**Comment by devlead** [comment]
Yes, .NET 4.6 is the requirement for Cake 0.22.0 and up, so upgrading Cake and as you already commented pinning Cake & addin versions is the recommended approach for reproducible builds.

**Comment by johnkors** [comment]
Thanks!
