### ISSUE TITLE
0.16.1 breaks build

### ISSUE THREAD

**Issue by bacobart** [cake-contrib/Cake_Git#49]
We' re getting the following error with the new 0.16.1 package:

Could not find any assemblies compatible with .NETFramework,Version=v4.5.
Error: Failed to install addin 'Cake.Git'.

0.16.0 was working fine. Cake version used is 0.21.1.

**Comment by gep13** [comment]
@bacobart have a look here:

https://github.com/cake-contrib/Cake_Git/issues/48

**Comment by devlead** [comment]
From Cake 0.22.0 and up .NET 4.6 is the target, to keep your builds running without surprises you could pin your Cake & addin versions, and upgrade them controlled.
Theres more info about this under  [Pinning Cake Version](https://cakebuild.net/docs/tutorials/pinning-cake-version) at the Cake web site.

**Comment by bacobart** [comment]
thanks -- but i would not have expected a breaking change like this in a minor version change.

**Comment by devlead** [comment]
Agree! Actually 0.16.0 was bumped to Cake.Core 0.22.0 and .NET 4.6... so it was a fluke that worked with older versions of Cake as there was several breaking changes. In 0.16.1 assembly was corrected to target right framwork moniker.
