### ISSUE TITLE
Cake Script Fails to install Cake.Git

### ISSUE THREAD

**Issue by JKSnd** [cake-contrib/Cake_Git#51]
I keep getting the error "Could not find any assemblies compatible with .NETFramework,Version=4.5 Error: Failed to install addin 'Cake.Git'"

I've tried a number of different things already including fixed versions of the addin, and trying to use previous releases. Nothing changes.

Any hints for me?

**Comment by devlead** [comment]
Clear tools folder and then pin to an earlier version of the Cake.Git addin or update to version 0.22.0 or later of Cake

Read more at:
https://cakebuild.net/docs/tutorials/pinning-cake-version

**Comment by JKSnd** [comment]
Have been pinned to cake 0.21.0 for a while. Good call on cleaning the tools folder. I rely on my build script to do a "git clean -fdx" on my build server for me, so locally this tripped me up. Pinning Cake.Git to 0.15.0 did the trick.

Thanks!
