### ISSUE TITLE
Tests for new alias methods cannot run with cake >= 0.26

### ISSUE THREAD

**Issue by mbeelman** [cake-contrib/Cake_Git#59]
While writing some additional alias methods for git tags, I detected the issue with the new version of cake 0.26. If the test runs with the previous used version 0.22 all tests passed.

After a rebase to master the test fails because the new alias method could not be found. The version 0.26.1 does not fix this issue.

When the test.cake file is executed, cake restores the Cake_Git package from the configured nuget feeds.

**Comment by devlead** [comment]
Yes noticed the same, you can't fool the new in proc nuget handling😎 think I'll know how to sort it.
