### ISSUE TITLE
GitLog returns only one commit when using sinceCommitId

### ISSUE THREAD

**Issue by Bounz** [cake-contrib/Cake_Git#75]
Hi!
Thank you for creating this addin!

It seems, that `GitLog(this ICakeContext context, DirectoryPath repositoryDirectoryPath, string sinceCommitId)` returns only one commit when it supposed to return all commits between `sinceCommitId` and `HEAD` (or maybe I misunderstood the purpose of this method).

If I am right and this is a bug then it could be easily fixed changing `CommitFilter` from
```
new CommitFilter
{
    IncludeReachableFrom = sinceCommitId,
    ExcludeReachableFrom = repository.Lookup<Commit>(sinceCommitId).Parents
}
```
to
```
new CommitFilter
{
    IncludeReachableFrom = repository.Head,
    ExcludeReachableFrom = repository.Lookup<Commit>(sinceCommitId).Parents
}
```
and I can submit a PR for this fix.

**Comment by devlead** [comment]
Sounds reasonable to me.

PR would be welcome along with a test in [test.cake](https://github.com/cake-contrib/Cake_Git/blob/develop/test.cake) to test this.

**Comment by Bounz** [comment]
PR is ready for review: https://github.com/cake-contrib/Cake_Git/pull/76

**Comment by mdesousa** [comment]
Hi, I also ran into this issue... glad to see that it's already fixed. Do you know if it's going to be released soon? Thanks.
