### ISSUE TITLE
Push to use deployment key

### ISSUE THREAD

**Issue by s-tino** [cake-contrib/Cake_Git#94]
I need to push to a private GitHub repository: the only I can do this today is by using the credentials of an actual GitHub user that has write access to the repository.

As the push is performed server side, it would be more scalable to be able to use GitHub [deploy keys](https://developer.github.com/v3/guides/managing-deploy-keys/).
Ideally, it would be nice to have a Push alias which takes a key as input.

**Comment by devlead** [comment]
SSH isn't supported by the underlying LibGit2Sharp 
There's an issue around SSH at libgit2/libgit2sharp#1422

Only atm is to use oauth tokens, which is tied to user and not repo
https://help.github.com/articles/git-automation-with-oauth-tokens/

If you want to scope it to a repo I would create a separate dedicated GH account with limited access.
